WARD_TO_ZONE = {
    "NARELA": "Narela",
    "BANKNER": "Narela",
    "HOLAMBI KALAN": "Narela",
    "ALIPUR": "Narela",
    "BAKHTAWARPUR": "Narela",
    "POOTH KALAN": "Narela",
    "BEGUMPUR": "Narela",
    "SHAHBAAD": "Narela",
    "POOTH KHURD": "Narela",
    "BAWANA": "Narela",
    "NANGAL THAKRAN": "Narela",
    "KANJHAWALA": "Narela",
    "RANI KHERA": "Narela",
    "NANGLOI": "Narela",
    "MUNDKA": "Narela",
    "NILOTHI": "Narela",
    "BURARI": "Civil Line",
    "KADIPUR": "Civil Line",
    "MUKUNDPUR": "Civil Line",
    "SANT NAGAR": "Civil Line",
    "JHARODA": "Civil Line",
    "TIMARPUR": "Civil Line",
    "MALKA GANJ": "Civil Line",
    "MUKHERJEE NAGAR": "Civil Line",
    "DHIRPUR": "Civil Line",
    "ADARSH NAGAR": "Civil Line",
    "AZADPUR": "Civil Line",
    "BHALSWA": "Civil Line",
    "JAHANGIR PURI": "Civil Line",
    "SARUP NAGAR": "Civil Line",
    "SAMAYPUR BADLI": "Civil Line",
    "ROHINI-A": "Rohini",
    "ROHINI-B": "Rohini",
    "RITHALA": "Rohini",
    "VIJAY VIHAR": "Rohini",
    "BUDH VIHAR": "Rohini",
    "KIRARI": "Rohini",
    "PREM NAGAR": "Rohini",
    "MUBARIKPUR": "Rohini",
    "NITHARI": "Rohini",
    "AMAN VIHAR": "Rohini",
    "MANGOL PURI": "Rohini",
    "SULTANPURI-A": "Rohini",
    "SULTANPURI-B": "Rohini",
    "JAWALAPURI": "Rohini",
    "NANGLOI JAT": "Rohini",
    "NIHAL VIHAR": "Rohini",
    "GURU HARKISHAN NAGAR": "Rohini",
    "MANGOLPURI-A": "Rohini",
    "MANGOLPURI-B": "Rohini",
    "ROHINI-C": "Rohini",
    "ROHINI-F": "Rohini",
    "ROHINI-E": "Rohini",
    "ROHINI-D": "Rohini",
    "SHALIMAR BAGH-A": "Keshavpuram",
    "SHALIMAR BAGH-B": "Keshavpuram",
    "PITAM PURA": "Keshavpuram",
    "SARASWATI VIHAR": "Keshavpuram",
    "PASCHIM VIHAR": "Keshavpuram",
    "RANI BAGH": "Keshavpuram",
    "KOHAT ENCLAVE": "Keshavpuram",
    "SHAKUR PUR": "Keshavpuram",
    "TRI NAGAR": "Keshavpuram",
    "KESHAV PURAM": "Keshavpuram",
    "ASHOK VIHAR": "Keshavpuram",
    "WAZIR PUR": "Keshavpuram",
    "SANGAM PARK": "Keshavpuram",
    "MODEL TOWN": "Keshavpuram",
    "KAMLA NAGAR": "Keshavpuram",
    "SHASTRI NAGAR": "City S.P. Zone",
    "KISHAN GANJ": "City S.P. Zone",
    "SADAR BAZAR": "City S.P. Zone",
    "CIVIL LINES": "City S.P. Zone",
    "CHANDNI CHOWK": "City S.P. Zone",
    "JAMA MASJID": "City S.P. Zone",
    "CHANDNI MAHAL": "City S.P. Zone",
    "DELHI GATE": "City S.P. Zone",
    "SITA RAM BAZAR": "City S.P. Zone",
    "BALLIMARAN": "City S.P. Zone",
    "RAM NAGAR": "City S.P. Zone",
    "QURAISH NAGAR": "City S.P. Zone",
    "PAHAR GANJ": "Karolbagh",
    "KAROL BAGH": "Karolbagh",
    "DEV NAGAR": "Karolbagh",
    "WEST PATEL NAGAR": "Karolbagh",
    "EAST PATEL NAGAR": "Karolbagh",
    "RANJEET NAGAR": "Karolbagh",
    "BALJEET NAGAR": "Karolbagh",
    "KARAM PURA": "Karolbagh",
    "MOTI NAGAR": "Karolbagh",
    "RAMESH NAGAR": "Karolbagh",
    "NARAINA": "Karolbagh",
    "INDER PURI": "Karolbagh",
    "RAJINDER NAGAR": "Karolbagh",
    "PUNJABI BAGH": "West Zone",
    "MADIPUR": "West Zone",
    "RAGHUBIR NAGAR": "West Zone",
    "VISHNU GARDEN": "West Zone",
    "RAJOURI GARDEN": "West Zone",
    "CHAUKHANDI NAGAR": "West Zone",
    "SUBHASH NAGAR": "West Zone",
    "HARI NAGAR": "West Zone",
    "FATEH NAGAR": "West Zone",
    "TILAK NAGAR": "West Zone",
    "KHYALA": "West Zone",
    "KESHOPUR": "West Zone",
    "JANAKPURI": "West Zone",
    "MAHAVEER ENCLAVE": "West Zone",
    "JANAK PURI WEST": "West Zone",
    "VIKAS PURI": "West Zone",
    "HASTSAL": "West Zone",
    "VIKAS NAGAR": "West Zone",
    "KUNWAR SINGH NAGAR": "West Zone",
    "BAPROLA": "West Zone",
    "SAINIK ENCLAVE": "West Zone",
    "MOHAN GARDEN": "West Zone",
    "NAWADA": "West Zone",
    "UTTAM NAGAR": "West Zone",
    "BINDA PUR": "West Zone",
    "DABRI": "Najafgarh Zone",
    "SAGARPUR": "Najafgarh Zone",
    "MANGLAPURI": "Najafgarh Zone",
    "DWARKA-B": "Najafgarh Zone",
    "DWARKA-A": "Najafgarh Zone",
    "MATIALA": "Najafgarh Zone",
    "KAKROLA": "Najafgarh Zone",
    "NANGLI SAKRAWATI": "Najafgarh Zone",
    "CHHAWALA": "Najafgarh Zone",
    "ISAPUR": "Najafgarh Zone",
    "NAJAFGARH": "Najafgarh Zone",
    "DICHAON KALAN": "Najafgarh Zone",
    "ROSHAN PURA": "Najafgarh Zone",
    "DWARKA-C": "Najafgarh Zone",
    "BIJWASAN": "Najafgarh Zone",
    "KAPASHERA": "Najafgarh Zone",
    "MAHIPALPUR": "Najafgarh Zone",
    "RAJ NAGAR": "Najafgarh Zone",
    "PALAM": "Najafgarh Zone",
    "MADHU VIHAR": "Najafgarh Zone",
    "MAHAVIR ENCLAVE": "Najafgarh Zone",
    "SADHU NAGAR": "Najafgarh Zone",
    "DARYAGANJ": "Central Zone",
    "SIDHARTHA NAGAR": "Central Zone",
    "LAJPAT NAGAR": "Central Zone",
    "ANDREWS GANJ": "Central Zone",
    "AMAR COLONY": "Central Zone",
    "KOTLA MUBARAKPUR": "Central Zone",
    "SANGAM VIHAR-C": "Central Zone",
    "SANGAM VIHAR-B": "Central Zone",
    "TUGHLAKABAD EXTENSION": "Central Zone",
    "SRI NIWAS PURI": "Central Zone",
    "KALKAJI": "Central Zone",
    "GOVIND PURI": "Central Zone",
    "HARKESH NAGAR": "Central Zone",
    "TUGHLAKABAD": "Central Zone",
    "PUL PEHLADPUR": "Central Zone",
    "BADARPUR": "Central Zone",
    "MOLARBAND": "Central Zone",
    "MEETHAPUR": "Central Zone",
    "HARI NAGAR EXTENSION": "Central Zone",
    "JAITPUR": "Central Zone",
    "MADANPUR KHADAR EAST": "Central Zone",
    "MADANPUR KHADAR WEST": "Central Zone",
    "SARITA VIHAR": "Central Zone",
    "ABUL FAZAL ENCLAVE": "Central Zone",
    "ZAKIR NAGAR": "Central Zone",
    "HAUZ KHAS": "South Zone",
    "MALVIYA NAGAR": "South Zone",
    "GREEN PARK": "South Zone",
    "MUNIRKA": "South Zone",
    "R.K. PURAM": "South Zone",
    "VASANT VIHAR": "South Zone",
    "LADO SARAI": "South Zone",
    "MEHRAULI": "South Zone",
    "VASANT KUNJ": "South Zone",
    "AYA NAGAR": "South Zone",
    "BHATI": "South Zone",
    "CHHATARPUR": "South Zone",
    "SAID-UL-AJAIB": "South Zone",
    "DEOLI": "South Zone",
    "TIGRI": "South Zone",
    "SANGAM VIHAR-A": "South Zone",
    "DAKSHIN PURI": "South Zone",
    "MADANGIR": "South Zone",
    "PUSHP VIHAR": "South Zone",
    "KHANPUR": "South Zone",
    "CHITARANJAN PARK": "South Zone",
    "CHIRAG DELHI": "South Zone",
    "GREATER KAILASH": "South Zone",
    "NEW ASHOK NAGAR": "South Zone",
    "MAYUR VIHAR PHASE-I": "South Zone",
    "TRILOKPURI": "South Zone",
    "KONDLI": "South Zone",
    "GHAROLI": "South Zone",
    "KALYANPURI": "South Zone",
    "MAYUR VIHAR PHASE-II": "South Zone",
    "PATPARGANJ": "South Zone",
    "VINOD NAGAR": "South Zone",
    "MANDAWALI": "South Zone",
    "PANDAV NAGAR": "South Zone",
    "LALITA PARK": "South Zone",
    "SHAKARPUR": "South Zone",
    "LAXMI NAGAR": "South Zone",
    "PREET VIHAR": "South Zone",
    "I.P. EXTENSION": "South Zone",
    "ANAND VIHAR": "South Zone",
    "VISHWAS NAGAR": "South Zone",
    "ANARKALI": "South Zone",
    "JAGAT PURI": "South Zone",
    "GEETA COLONY": "South Zone",
    "KRISHNA NAGAR": "South Zone",
    "GANDHI NAGAR": "South Zone",
    "SHASTRI PARK": "South Zone",
    "AZAD NAGAR": "South Zone",
    "SHAHDARA": "South Zone",
    "JHILMIL": "Shahdara North Zone",
    "DILSHAD COLONY": "Shahdara North Zone",
    "SUNDAR NAGRI": "Shahdara North Zone",
    "DILSHAD GARDEN": "Shahdara North Zone",
    "NAND NAGRI": "Shahdara North Zone",
    "ASHOK NAGAR": "Shahdara North Zone",
    "RAM NAGAR EAST": "Shahdara North Zone",
    "ROHTASH NAGAR": "Shahdara North Zone",
    "WELCOME COLONY": "Shahdara North Zone",
    "SEELAMPUR": "Shahdara North Zone",
    "GAUTAM PURI": "Shahdara North Zone",
    "CHAUHAN BANGER": "Shahdara North Zone",
    "MAUJPUR": "Shahdara North Zone",
    "BRAHAM PURI": "Shahdara North Zone",
    "BHAJANPURA": "Shahdara North Zone",
    "GHONDA": "Shahdara North Zone",
    "YAMUNA VIHAR": "Shahdara North Zone",
    "SUBHASH MOHALLA": "Shahdara North Zone",
    "KABIR NAGAR": "Shahdara North Zone",
    "GORAKH PARK": "Shahdara North Zone",
    "KARDAM PURI": "Shahdara North Zone",
    "HARSH VIHAR": "Shahdara North Zone",
    "SABOLI": "Shahdara North Zone",
    "GOKAL PURI": "Shahdara North Zone",
    "JOHARIPUR": "Shahdara North Zone",
    "KARAWAL NAGAR-EAST": "Shahdara North Zone",
    "DAYALPUR": "Shahdara North Zone",
    "MUSTAFABAD": "Shahdara North Zone",
    "NEHRU VIHAR": "Shahdara North Zone",
    "BRIJ VIHAR": "Shahdara North Zone",
    "SRI RAM COLONY": "Shahdara North Zone",
    "SADATPUR": "Shahdara North Zone",
    "KARAWAL NAGAR-WEST": "Shahdara North Zone",
    "SONIA VIHAR": "Shahdara North Zone",
    "SABAPUR": "Shahdara North Zone"
}


def get_zone_for_ward(ward_name):
    import difflib
    if not ward_name: return 'Unknown Zone'
    ward_name = str(ward_name).upper()
    
    if 'NDMC' in ward_name or 'CANTT' in ward_name:
        return 'NDMC & Delhi Cantonment'
        
    # Try exact match
    if ward_name in WARD_TO_ZONE:
        return WARD_TO_ZONE[ward_name]
        
    # Try partial match
    for name, zone in WARD_TO_ZONE.items():
        if len(name) > 3 and name in ward_name:
            return zone
        if len(ward_name) > 3 and ward_name in name:
            return zone
            
    # Try fuzzy match
    matches = difflib.get_close_matches(ward_name, WARD_TO_ZONE.keys(), n=1, cutoff=0.6)
    if matches:
        return WARD_TO_ZONE[matches[0]]
        
    return 'Unknown Zone'
